from django.urls import path
from . import views

urlpatterns = [
    path("card-icons/", views.list_icons, name="avatar-list-icons"),
    path("card-icons/my/", views.my_icons, name="avatar-my-icons"),
    path("card-icons/shop/", views.shop_list_icons, name="avatar-shop-list"),
    path("card-icons/grant/", views.grant_icon, name="avatar-grant-icon"),
    path("card-icons/<int:icon_id>/purchase/", views.purchase_icon, name="avatar-purchase-icon"),
    path("card-icons/create/", views.create_icon, name="avatar-create-icon"),
    path("card-icons/<int:icon_id>/", views.update_icon, name="avatar-update-icon"),
    path("card-icons/<int:icon_id>/delete/", views.delete_icon, name="avatar-delete-icon"),
    path("card-icons/<int:icon_id>/set-new/", views.set_icon_new, name="avatar-set-icon-new"),
    path("card-icons/bulk-theme/", views.bulk_set_theme, name="avatar-bulk-theme"),
    path("card-icons/search-cards/", views.search_cards, name="avatar-search-cards"),
    path("card-icons/custom-illusts/", views.list_custom_illusts, name="avatar-custom-illusts"),
    path("card-icons/custom-illusts/upload/", views.upload_custom_illust, name="avatar-custom-illust-upload"),
    path("card-icons/custom-illusts/bulk-upload/", views.bulk_upload_custom_illusts, name="avatar-custom-illust-bulk"),
    path("card-icons/custom-illusts/twitter-credentials/", views.twitter_credentials, name="avatar-twitter-credentials"),
    path("card-icons/custom-illusts/scrape-twitter/", views.scrape_twitter_range, name="avatar-scrape-twitter"),
    path("card-icons/custom-illusts/import-tweet/", views.import_tweet_illusts, name="avatar-custom-illust-import-tweet"),
    path("card-icons/custom-illusts/<int:illust_id>/delete/", views.delete_custom_illust, name="avatar-custom-illust-delete"),
    path("card-icons/themes/", views.list_themes, name="avatar-list-themes"),
    path("me/", views.my_avatar, name="avatar-me"),
    path("me/set/", views.set_my_avatar, name="avatar-set-me"),
    path("borders/me/", views.my_borders, name="avatar-my-borders"),
    path("borders/me/set/", views.set_my_border, name="avatar-set-my-border"),
    path("borders/grant/", views.grant_border, name="avatar-grant-border"),
    path("borders/shop/", views.shop_list_borders, name="avatar-shop-borders"),
    path("borders/admin/", views.list_borders_admin, name="avatar-list-borders-admin"),
    path("borders/<int:border_id>/purchase/", views.purchase_border, name="avatar-purchase-border"),
    path("borders/<int:border_id>/", views.update_border, name="avatar-update-border"),
]
