"""Solo 딱무고개 REST views — start game, ask question, attempt guess.

One active game per user; starting a new game silently abandons any
in-progress one. Daily points cap is shared with Solo Duchmind via
SoloDailyPoints (so a user can't farm both modes past the unified ceiling).
"""
import random
from django.db import transaction
from django.utils import timezone
from rest_framework.decorators import api_view, permission_classes
from rest_framework.permissions import IsAuthenticated
from rest_framework.response import Response

from .models import (
    SoloTwentyGame,
    SOLO_TW_QUESTION_BUDGET,
    SOLO_TW_SCORE_LADDER,
    SOLO_DAILY_POINTS_CAP,
)
from .twenty_engine import (
    answer_question,
    build_question_text,
    build_menu,
    build_guess_comparison,
    resolve_hint,
    hint_remaining_per_dim,
    HINT_DIMS,
    score_for,
)
from card.models import Card
from .models import SOLO_TW_HINT_PENALTIES, SOLO_TW_MAX_HINTS
from .views import _get_or_create_daily, _today

# Source identifier for the per-game daily ledger — separates Twenty's
# 100P cap from the duchmind cap. Keep in sync with SOLO_SOURCE_TWENTY in
# solo/models.py.
_DAILY_SOURCE = "twenty"


def _twenty_daily(user, *, lock: bool = False):
    return _get_or_create_daily(user, lock=lock, source=_DAILY_SOURCE)


def _today_points(user) -> int:
    """How many points the user has already earned today via 딱무고개. Used
    by both the current_game endpoint and the post-guess payload."""
    from .models import SoloDailyPoints
    return (
        SoloDailyPoints.objects
        .filter(user=user, date=_today(), source=_DAILY_SOURCE)
        .values_list("points_earned", flat=True).first() or 0
    )


DIFFICULTY_CHOICES = ("초급", "중급", "고급")
# Per-difficulty daily ceiling. 초급 keeps the legacy 100P cap (recommended
# starting point); 중급 unlocks +50P (up to 150); 고급 unlocks +50P more
# (up to 200). All three share one ledger row (SOURCE_TWENTY), so a player
# who tops out 초급 at 100P needs to play 중급/고급 to keep earning.
SOLO_TW_DIFFICULTY_CAPS = {"초급": 100, "중급": 150, "고급": 200}
SOLO_TW_DAILY_POINTS_CAP_ABS = 200


def _pool_card_ids(difficulty: str = "중급", exclude_st: bool = False):
    """Pull the card-id pool for solo 딱무고개 from the named DuchMind
    word pack (초급/중급/고급), excluding cards with no Yugipedia data
    at all (every yp_* property empty). Those cards always answer 'no'
    to yp_* cluster questions, which wastes the player's budget. Normal
    monsters still pass — Yugipedia tags them with generic 'Can be X /
    Non-X' descriptors, so their props are non-empty.

    When exclude_st=True, Spell/Trap cards are also filtered out so
    players who only want to guess monsters aren't surprised by an ST.
    """
    from multiplayer.models import DuchMindWord, DuchMindWordPack
    from django.db.models import Q
    if difficulty not in DIFFICULTY_CHOICES:
        difficulty = "중급"
    pack = DuchMindWordPack.objects.filter(name=difficulty).first()
    if not pack:
        return []
    all_empty = (
        Q(card__yugipedia_actions=[])
        & Q(card__yugipedia_summoning=[])
        & Q(card__yugipedia_misc=[])
        & Q(card__yugipedia_monster_spell_trap=[])
        & Q(card__yugipedia_banishing=[])
    )
    qs = DuchMindWord.objects.filter(pack=pack, enabled=True, card__isnull=False).exclude(all_empty)
    # Tokens are generated by other cards, not "cards to guess"; always
    # exclude them. Cards whose Korean name still equals the English name
    # are unreleased in Korea (e.g. "ALERT!", "EXTINGUISH!"), exclude too
    # — players have no way to recall an EN-only card name.
    qs = qs.exclude(card__frame_type="token")
    qs = qs.extra(where=["card_card.korean_name != card_card.name"])
    if exclude_st:
        qs = qs.exclude(card__frame_type__in=["spell", "trap"])
    # Dedupe by korean_name so multi-alt-art cards (e.g. 죽은 자의 소생 has 4
    # rows for one name) don't get inflated draw probability. Keep the
    # row with the lowest card_id — that's the original printing.
    seen_names: set[str] = set()
    pool: list[int] = []
    for pk, kr in qs.select_related("card").order_by("card__card_id").values_list("card_id", "card__korean_name"):
        if kr in seen_names:
            continue
        seen_names.add(kr)
        pool.append(pk)
    return pool


def _public_game_payload(game: SoloTwentyGame) -> dict:
    """Public view of a game — never includes the secret card identity
    while the game is `active`. Card details are revealed once status flips
    to `won` or `lost`."""
    out = {
        "id": game.id,
        "questions_used": game.questions_used,
        "questions_remaining": max(0, SOLO_TW_QUESTION_BUDGET - game.questions_used),
        "total_questions": SOLO_TW_QUESTION_BUDGET,
        "history": list(game.history or []),
        "status": game.status,
        "difficulty": game.difficulty or "중급",
        "exclude_st": bool(game.exclude_st),
        "hints_used": game.hints_used or 0,
        "hints_max": SOLO_TW_MAX_HINTS,
        "hint_remaining_per_dim": (
            hint_remaining_per_dim(game.card, list(game.history or []))
            if game.card and game.status == "active" else {}
        ),
        "points_awarded": game.points_awarded,
        "started_at": game.started_at.isoformat() if game.started_at else None,
        "ended_at": game.ended_at.isoformat() if game.ended_at else None,
    }
    if game.status != "active" and game.card_id:
        c = game.card
        try:
            illust = c.card_illust.url if c.card_illust else None
        except Exception:
            illust = None
        out["answer"] = {
            "card_id": c.card_id,
            "name": game.card_name_snapshot or c.korean_name or c.name,
            "image_url": illust or c.image_url,
        }
    return out


@api_view(["GET"])
@permission_classes([IsAuthenticated])
def menu(request):
    """Return the structured question menu (groups → items). Cached on the
    server side but cheap enough to recompute every request. The 카드군
    group's items depend on the pool, so accept ?difficulty=초급/중급/고급
    and ?exclude_st=1 (monsters-only pool)."""
    difficulty = (request.GET.get("difficulty") or "중급").strip()
    if difficulty not in DIFFICULTY_CHOICES:
        difficulty = "중급"
    exclude_st = request.GET.get("exclude_st") in ("1", "true", "True")
    return Response({
        "menu": build_menu(difficulty=difficulty, exclude_st=exclude_st),
        "total_questions": SOLO_TW_QUESTION_BUDGET,
        "score_ladder": SOLO_TW_SCORE_LADDER,
    })


@api_view(["POST"])
@permission_classes([IsAuthenticated])
def start_game(request):
    """Start a fresh solo 딱무고개 game. If the user already has an active
    game, mark it as `lost` (abandoned) before creating the new one — keeps
    the "one active game per user" invariant clean."""
    user = request.user
    difficulty = (request.data.get("difficulty") or "중급").strip()
    if difficulty not in DIFFICULTY_CHOICES:
        return Response({"error": "난이도가 잘못 지정되었습니다."}, status=400)
    exclude_st = bool(request.data.get("exclude_st"))
    pool = _pool_card_ids(difficulty, exclude_st=exclude_st)
    if not pool:
        return Response({"error": "단어장이 비어 있습니다."}, status=503)
    card_id = random.choice(pool)
    try:
        card = Card.objects.get(id=card_id)
    except Card.DoesNotExist:
        return Response({"error": "카드를 찾을 수 없습니다."}, status=500)

    with transaction.atomic():
        # Abandon any prior active game.
        SoloTwentyGame.objects.filter(user=user, status="active").update(
            status="lost", ended_at=timezone.now(),
        )
        game = SoloTwentyGame.objects.create(
            user=user,
            card=card,
            card_name_snapshot=card.korean_name or card.name or "",
            questions_used=0,
            history=[],
            status="active",
            difficulty=difficulty,
            exclude_st=exclude_st,
        )
    return Response(_public_game_payload(game))


@api_view(["GET"])
@permission_classes([IsAuthenticated])
def current_game(request):
    """Resume endpoint — returns the active game (or null) plus today's
    daily-points context. Used on page load to restore the UI."""
    user = request.user
    game = (SoloTwentyGame.objects
            .filter(user=user, status="active")
            .order_by("-started_at").first())
    today_pts = _today_points(user)
    return Response({
        "game": _public_game_payload(game) if game else None,
        "points_earned_today": today_pts,
        "daily_points_cap": SOLO_TW_DAILY_POINTS_CAP_ABS,
        "points_remaining_today": max(0, SOLO_TW_DAILY_POINTS_CAP_ABS - today_pts),
        "difficulty_caps": SOLO_TW_DIFFICULTY_CAPS,
    })


def _award_points_if_won(user, used: int, difficulty: str = "중급", hints_used: int = 0) -> tuple[int, bool]:
    """Compute + persist the tiered solve reward, honoring the
    difficulty-specific daily cap. Returns (paid_points, cap_reached_flag).
    A 초급 game cannot push the daily total past 100P, 중급 past 150P,
    고급 past 200P — but they share one ledger, so a player who maxed
    초급 (100P) can still earn 50P more by playing 중급. Hint usage
    subtracts a cumulative penalty (SOLO_TW_HINT_PENALTIES)."""
    base = score_for(used, SOLO_TW_SCORE_LADDER)
    if base <= 0:
        return 0, False
    penalty = SOLO_TW_HINT_PENALTIES[min(hints_used, SOLO_TW_MAX_HINTS)]
    base = max(0, base - penalty)
    if base <= 0:
        return 0, False
    cap = SOLO_TW_DIFFICULTY_CAPS.get(difficulty, 100)
    with transaction.atomic():
        daily = _twenty_daily(user, lock=True)
        remaining = max(0, cap - daily.points_earned)
        paid = min(base, remaining)
        cap_reached = (remaining == 0)
        if paid > 0:
            # Late import to avoid circular: solo.views → solo.twenty_views.
            from user.points import award_points
            award_points(user, paid, kind="game_twenty",
                         note=f"솔로 딱무고개 정답 ({used}질문)")
            daily.points_earned = daily.points_earned + paid
            daily.save(update_fields=["points_earned"])
        return paid, cap_reached


@api_view(["POST"])
@permission_classes([IsAuthenticated])
def ask_question(request):
    """Submit a structured question. Body: {game_id, q_type, q_value}.
    Returns the updated public game payload (with the new history entry +
    decremented budget); auto-loses when budget hits zero."""
    user = request.user
    game_id = request.data.get("game_id")
    q_type = request.data.get("q_type") or ""
    q_value = request.data.get("q_value")
    try:
        game = SoloTwentyGame.objects.select_for_update().get(id=game_id, user=user)
    except SoloTwentyGame.DoesNotExist:
        return Response({"error": "게임을 찾을 수 없습니다."}, status=404)
    if game.status != "active":
        return Response({"error": "이미 종료된 게임입니다."}, status=400)
    # Asks are budget-limited; once 20 questions are spent, the player
    # still gets ONE final guess (handled in guess_card), but no more asks.
    if game.questions_used >= SOLO_TW_QUESTION_BUDGET:
        return Response({"error": "질문을 모두 사용했습니다. 마지막 정답 시도만 가능합니다."}, status=400)
    try:
        ans = answer_question(game.card, q_type, q_value)
    except ValueError:
        return Response({"error": "알 수 없는 질문 종류입니다."}, status=400)

    with transaction.atomic():
        game = SoloTwentyGame.objects.select_for_update().get(id=game.id)
        if game.status != "active":
            return Response({"error": "이미 종료된 게임입니다."}, status=400)
        game.questions_used += 1
        history = list(game.history or [])
        history.append({
            "kind": "ask",
            "q_type": q_type,
            "q_value": q_value,
            "q_text": build_question_text(q_type, q_value),
            "answer": bool(ans),
        })
        game.history = history
        # No auto-lose here — at budget cap, the player still has the final
        # guess. The game ends inside guess_card if that final guess misses.
        game.save(update_fields=["questions_used", "history"])
    return Response(_public_game_payload(game))


@api_view(["POST"])
@permission_classes([IsAuthenticated])
def guess_card(request):
    """Submit a card guess. Body: {game_id, card_name}. One question of the
    budget is consumed. Correct guess wins (and awards points up to the
    daily cap). Matching is by korean_name (the snapshot taken at game
    start) so a card rename can't invalidate an in-flight guess."""
    user = request.user
    game_id = request.data.get("game_id")
    guess_name = (request.data.get("card_name") or "").strip()
    if not guess_name:
        return Response({"error": "카드를 선택해 주세요."}, status=400)
    try:
        game = SoloTwentyGame.objects.get(id=game_id, user=user)
    except SoloTwentyGame.DoesNotExist:
        return Response({"error": "게임을 찾을 수 없습니다."}, status=404)
    if game.status != "active":
        return Response({"error": "이미 종료된 게임입니다."}, status=400)
    # One extra guess is allowed past the budget — the "final attempt".
    # questions_used == BUDGET means the player exhausted asks; this guess
    # bumps to BUDGET+1 and (on miss) ends the game.
    if game.questions_used > SOLO_TW_QUESTION_BUDGET:
        return Response({"error": "정답 시도를 이미 사용했습니다."}, status=400)

    correct = guess_name == (game.card_name_snapshot or "")

    paid = 0
    cap_reached = False
    with transaction.atomic():
        game = SoloTwentyGame.objects.select_for_update().get(id=game.id)
        if game.status != "active":
            return Response({"error": "이미 종료된 게임입니다."}, status=400)
        is_final = game.questions_used >= SOLO_TW_QUESTION_BUDGET
        game.questions_used += 1
        history = list(game.history or [])
        entry = {
            "kind": "guess",
            "q_type": "guess",
            "q_value": guess_name,
            "q_text": f"정답 시도: {guess_name}",
            "answer": bool(correct),
            "choice_name": guess_name,
        }
        if not correct:
            # Look up the guessed card to show partial-match feedback.
            # Skip if guess didn't resolve to a card (typo/non-existent).
            guess_card_obj = Card.objects.filter(korean_name=guess_name).first()
            if guess_card_obj and game.card:
                entry["comparison"] = build_guess_comparison(game.card, guess_card_obj)
        history.append(entry)
        game.history = history
        if correct:
            game.status = "won"
            game.ended_at = timezone.now()
        elif is_final:
            game.status = "lost"
            game.ended_at = timezone.now()
        game.save(update_fields=["questions_used", "history", "status", "ended_at"])
        if correct:
            paid, cap_reached = _award_points_if_won(
                user, game.questions_used,
                game.difficulty or "중급",
                hints_used=game.hints_used or 0,
            )
            if paid > 0:
                game.points_awarded = paid
                game.save(update_fields=["points_awarded"])

    today_pts = (
        type(_get_or_create_daily(user)).objects
        .filter(user=user, date=_today(), source=_DAILY_SOURCE)
        .values_list("points_earned", flat=True).first() or 0
    )
    payload = _public_game_payload(game)
    payload.update({
        "points_awarded": paid,
        "cap_reached": cap_reached,
        "points_earned_today": today_pts,
        "daily_points_cap": SOLO_TW_DAILY_POINTS_CAP_ABS,
        "points_remaining_today": max(0, SOLO_TW_DAILY_POINTS_CAP_ABS - today_pts),
        "difficulty_caps": SOLO_TW_DIFFICULTY_CAPS,
    })
    return Response(payload)


@api_view(["GET"])
@permission_classes([IsAuthenticated])
def hint_dims(request):
    """List the hint dimensions the FE can offer + the current penalty
    ladder. FE renders one button per dim in the hint picker modal."""
    return Response({
        "dims": [{"dim": d, "label": label} for d, label in HINT_DIMS],
        "penalties": SOLO_TW_HINT_PENALTIES,
        "max_hints": SOLO_TW_MAX_HINTS,
    })


@api_view(["POST"])
@permission_classes([IsAuthenticated])
def use_hint(request):
    """Reveal one dimension of the secret card. Body: {game_id, dim}.
    Increments hints_used, appends a 'hint' entry to history, returns
    the updated game. Capped at SOLO_TW_MAX_HINTS per game."""
    user = request.user
    game_id = request.data.get("game_id")
    dim = (request.data.get("dim") or "").strip()
    if dim not in {d for d, _ in HINT_DIMS}:
        return Response({"error": "지원하지 않는 힌트 종류입니다."}, status=400)
    try:
        game = SoloTwentyGame.objects.get(id=game_id, user=user)
    except SoloTwentyGame.DoesNotExist:
        return Response({"error": "게임을 찾을 수 없습니다."}, status=404)
    if game.status != "active":
        return Response({"error": "이미 종료된 게임입니다."}, status=400)
    if not game.card:
        return Response({"error": "정답 카드를 찾을 수 없습니다."}, status=500)
    with transaction.atomic():
        game = SoloTwentyGame.objects.select_for_update().get(id=game.id)
        if game.status != "active":
            return Response({"error": "이미 종료된 게임입니다."}, status=400)
        if (game.hints_used or 0) >= SOLO_TW_MAX_HINTS:
            return Response({"error": "힌트를 모두 사용했습니다."}, status=400)
        history = list(game.history or [])
        # Effect/Cost/Trigger dims can be asked repeatedly — each call
        # reveals a fresh cluster. Other dims (frame/attribute/race/...)
        # are single-use; reject if already asked.
        remaining = hint_remaining_per_dim(game.card, history)
        if remaining.get(dim, 0) <= 0:
            return Response({"error": "이 종류의 힌트는 더 알려줄 게 없습니다."}, status=400)
        try:
            value = resolve_hint(game.card, dim, history)
        except ValueError:
            return Response({"error": "이 종류의 힌트는 더 알려줄 게 없습니다."}, status=400)
        dim_label = dict(HINT_DIMS).get(dim, dim)
        history.append({
            "kind": "hint",
            "q_type": f"hint_{dim}",
            "q_value": dim,
            "q_text": f"💡 힌트: {dim_label} → {value}",
            "answer": True,
            "hint_dim": dim,
            "hint_label": dim_label,
            "hint_value": value,
        })
        game.hints_used = (game.hints_used or 0) + 1
        game.history = history
        game.save(update_fields=["hints_used", "history"])
    return Response(_public_game_payload(game))


@api_view(["POST"])
@permission_classes([IsAuthenticated])
def give_up(request):
    """Abandon the current active game without using any more budget — the
    answer is revealed but no points awarded."""
    user = request.user
    game_id = request.data.get("game_id")
    try:
        game = SoloTwentyGame.objects.get(id=game_id, user=user)
    except SoloTwentyGame.DoesNotExist:
        return Response({"error": "게임을 찾을 수 없습니다."}, status=404)
    if game.status != "active":
        return Response({"error": "이미 종료된 게임입니다."}, status=400)
    game.status = "lost"
    game.ended_at = timezone.now()
    game.save(update_fields=["status", "ended_at"])
    return Response(_public_game_payload(game))
