"""Yugipedia tag clusters for the solo Twenty Questions game.

Manual taxonomy that collapses ~700 Yugipedia SMW values (across Actions,
Summoning, Misc, MonsterSpellTrap, Banishing properties) into ~60
player-facing question categories. Built collaboratively with the user
2026-05; see chat history for rationale on individual decisions.

The taxonomy is organized into three top-level groups (matching the
game menu groups: 발동 비용 / 효과 / 발동 시점):
  - cost_*    : "발동에 X가 필요한 카드인가요?"
  - effect_*  : "X를 하는 카드인가요?"
  - trigger_* : "X 상황에서 발동하는 카드인가요?"
"""

# Map: cluster_id → set of exact Yugipedia value strings (case-sensitive).
# A card belongs to a cluster if ANY of its Yugipedia values (across all 5
# properties: actions, summoning, misc, monster_spell_trap, banishing) is in
# the cluster's set.
CLUSTERS: dict[str, set[str]] = {

    # ─────────────── 그룹 ①: 발동 비용 (Cost) ───────────────

    "cost_tribute": {
        "Tributes for cost",
        "Tributes itself for cost",
        "Tributes from hand for cost",
        "Tributes from field for cost",
        "Tributes for Special Summon",
    },
    "cost_discard": {
        "You discard for cost",
        "Discards itself for cost",
        "Discards for cost",
        "Sends from hand to Graveyard for cost",
    },
    "cost_field_to_gy": {
        "Sends from field to Graveyard for cost",
        "Sends itself from field to Graveyard for cost",
    },
    "cost_reveal_hand": {
        "Reveals your hand for cost",
        "Reveals itself in the hand for cost",
        "Reveals your Extra Deck for cost",
    },
    "cost_send_deck_to_gy": {
        "Sends from Deck to Graveyard for cost",
        "Sends from the top of your Deck to your Graveyard for cost",
        "Sends from Extra Deck to Graveyard for cost",
    },
    "cost_bounces": {
        "Returns from field to hand for cost",
        "Returns from field to Deck for cost",
        "Returns from field to Extra Deck for cost",
        "Returns itself from field to hand for cost",
        "Returns itself from field to Deck for cost",
        "Returns itself from field to Extra Deck for cost",
    },
    "cost_return_hand_to_deck": {
        "Returns from hand to Deck for cost",
        "Returns from hand to Deck for Summon",
        "Returns itself from hand to Deck for cost",
    },
    "cost_banish": {
        # Banishing property "X for cost" variants.
        "Banishes itself from Graveyard for cost",
        "Banishes from Graveyard for cost",
        "Banishes from hand for cost",
        "Banishes from field for cost",
        "Banishes itself from field for cost",
        "Banishes from Extra Deck for cost",
    },

    # ─────────────── 그룹 ②: 효과 (Effect) ───────────────

    "effect_destroys_monster": {
        "Destroys Monster Cards",
        "Destroys your opponent's Monster Cards",
        "Destroys your Monster Cards",
        "Destroys face-up Monster Cards",
        "Destroys your face-up Monster Cards",
        "Destroys your opponent's face-up Monster Cards",
    },
    "effect_destroys_st": {
        "Destroys Spell Cards",
        "Destroys Trap Cards",
        "Destroys your opponent's Spell Cards",
        "Destroys your opponent's Trap Cards",
        "Destroys your Spell Cards",
        "Destroys your Trap Cards",
    },
    "effect_negates_activation": {
        "Negates the activation of Spell Cards",
        "Negates the activation of Trap Cards",
        "Negates the activation of Effect Monster's effect",
        "Negates the activation of your opponent's Spell Cards",
        "Negates the activation of your opponent's Trap Cards",
        "Negates the activation of your opponent's Effect Monster's effect",
    },
    "effect_negates_effect": {
        "Negates the effects of your opponent's Effect Monsters",
        "Negates the effects of the Summoned monsters",
        "Negates the effects of Effect Monsters",
        "Negates the effects of Spell Cards",
        "Negates the effects of your opponent's Spell Cards",
        "Negates the effects of Trap Cards",
        "Negates the effects of your opponent's Trap Cards",
        "Negates the effects of your opponent's Effect Monsters' effects",
    },
    "effect_searches": {
        "Adds from Deck to hand",
        "Adds from your opponent's Deck to your opponent's hand",
        "Adds from your opponent's Deck to your hand",
    },
    "effect_salvages": {
        "Adds from Graveyard to hand",
        "Returns from your Graveyard to your hand",
        "Returns itself from Graveyard to hand",
        "Returns from your opponent's Graveyard to your opponent's hand",
        "Returns from your opponent's Graveyard to your hand",
    },
    "effect_draws": {
        "You draw cards",
    },
    "effect_dumps_own_deck": {
        "Sends from your Deck to your Graveyard",
        "Sends from the top of your Deck to your Graveyard",
    },
    "effect_mills_opponent_deck": {
        "Sends from your opponent's Deck to your opponent's Graveyard",
        "Sends from the top of your opponent's Deck to your opponent's Graveyard",
    },
    "effect_dumps_own_extra": {
        "Sends from your Extra Deck to your Graveyard",
    },
    "effect_mills_opponent_extra": {
        "Sends from your opponent's Extra Deck to your opponent's Graveyard",
    },
    "effect_bounces": {
        # Field → hand/deck/extra (any owner). NO "for cost" variants.
        "Returns from your opponent's field to your opponent's hand",
        "Returns from your field to your hand",
        "Returns itself from field to hand",
        "Returns from field to hand",
        "Returns from field to Deck",
        "Returns from your field to your Deck",
        "Returns from your opponent's field to your opponent's Deck",
        "Returns from field to Extra Deck",
        "Returns from your field to your Extra Deck",
        "Returns from your opponent's field to your opponent's Extra Deck",
        "Returns itself from field to Deck",
        "Returns itself from field to Extra Deck",
        "Returns from your opponent's field to your hand",
        "Returns from your field to your opponent's hand",
    },
    "effect_sends_field_to_gy": {
        "Sends from your field to your Graveyard",
        "Sends from field to Graveyard",
        "Sends from your opponent's field to your opponent's Graveyard",
        "Sends itself from field to Graveyard",
    },
    "effect_changes_battle_position": {
        "Changes battle positions",
        "Changes own battle position",
    },
    "effect_flips_face_position": {
        "Flips itself face-down",
        "Flips monsters face-down",
        "Flips your opponent's monsters face-down",
        "Flips monsters face-up",
        "Flips your monsters face-down",
        "Flips itself face-up",
        "Flips your monsters face-up",
        "Flips your opponent's monsters face-up",
    },
    "effect_discards": {
        "Sends from your hand to your Graveyard",
        "You discard as an effect",
        "Sends from hand to Graveyard",
    },
    "effect_recycles_gy_to_deck": {
        "Returns from your Graveyard to your Deck",
        "Returns from Graveyard to Deck",
        "Returns itself from Graveyard to Deck",
        "Returns from your opponent's Graveyard to your opponent's Deck",
        "Returns from your Graveyard to your Extra Deck",
        "Returns from Graveyard to Extra Deck",
        "Returns from Graveyard to Deck for cost",
        "Returns itself from Graveyard to Deck",
        "Returns from Graveyard to Deck for Summon",
    },
    "effect_equip_mechanic": {
        "Equips self from field",
        "Equips self from Graveyard",
        "Equips self from hand",
        "Equips self while banished",
        "Equips monsters from the player's field to itself",
        "Equips monsters from the opponent's field to itself",
        "Equips monsters from the player's Graveyard to itself",
        "Equips from the player's Graveyard",
        "Equips from the player's Deck",
        "Equips from the player's hand",
        "Equips monsters from the player's Deck",
        "Equips monsters from the opponent's field",
        "Equips monsters from the player's Graveyard",
        "Equips monsters from the player's hand",
        "Equips monsters from the player's Deck to itself",
        "Equips from the player's Graveyard to itself",
        "Equips from the player's hand to itself",
        "Equips from the player's Deck to itself",
        "Equips monsters from the opponent's Graveyard to itself",
        "Equips from the player's Extra Deck",
        "Equips from the opponent's Graveyard",
        "Equips the player's banished monsters",
        "Equips the player's banished monsters to itself",
        "Equips monsters from the player's field",
        "Equips monsters from the opponent's Graveyard",
        "Equips from the player's Extra Deck to itself",
    },
    "effect_sets_from_deck": {
        "Sets from your Deck",
    },
    "effect_sets_from_hand": {
        "Sets from your hand",
        "Sets itself from the hand as a Spell Card",
    },
    "effect_sets_from_gy_or_banished": {
        "Sets from your Graveyard",
        "Sets itself from your Graveyard",
        "Sets the player's banished cards",
        "Sets your opponent's banished cards",
        "Sets itself while banished",
        "Sets the opponent's banished cards to the player's field",
        "Sets the opponent's banished cards to the opponent's field",
        "Sets the player's banished cards to the opponent's field",
    },
    "effect_control_change": {
        "Takes control of an opponent's monster",
        "Gives control of your monster",
        "Changes control",
        "Takes control of equipped",
    },
    "effect_locks": {
        # Filtered to opponent/universal restrictions, NOT self-only.
        "Prevents your opponent's Special Summons",
        "Prevents your opponent's Normal Summons",
        "Prevents your opponent's Sets",
        "Prevents your opponent's Flip Summons",
        "Prevents the opponent's Tributes",
        "Prevents the opponent placing cards on the field",
        "Restricts the opponent's Normal Summons",
        "Restricts the opponent's Flip Summons",
        "Restricts the opponent's Special Summons",
        "Prevents Special Summons",
        "Prevents Normal Summons",
        "Prevents Synchro Summons",
        "Prevents Xyz Summons",
        "Prevents Link Summons",
        "Prevents Fusion Summons",
        "Prevents Flip Summons",
        "Prevents Tribute Summons",
        "Prevents battle position changes",
        "Prevents drawing cards",
        "Prevents adding cards from Deck to hand",
        "Prevents sending cards from Deck to Graveyard",
        "Prevents returning cards from field to Extra Deck",
        "Prevents cards from being discarded",
        "Prevents responding to its activation",
    },
    "effect_returns_banished_to_hand": {
        "Adds banished cards to the hand",
        "Adds banished cards to the Extra Deck",
        "Adds your opponent's banished cards to your hand",
        "Adds your banished cards to your opponent's hand",
        "Adds from your opponent's Graveyard to your hand",
    },
    "effect_forces_opponent_discard": {
        # "패를 버리거나 파괴하는" — opponent-forced discard + any hand
        # destruction (악의 덱 파괴 바이러스, 마인드 크러시 류). User
        # rationale: discard and destroy-from-hand are mechanically
        # distinct but read the same to the asker.
        "Your opponent discards",
        "Makes your opponent send from the hand to the Graveyard",
        "Sends from your opponent's hand to your opponent's Graveyard",
        "Destroys hand",
    },
    "effect_forces_opponent_draw": {
        "Your opponent draws cards",
    },
    "effect_fusion_related": {
        # Effect performs a fusion summon or actively uses cards as fusion
        # material. Excludes generic "Can be Fusion Summoned" / "Can be used
        # as a Fusion Material" which apply to ~every monster.
        "Performs a Fusion Summon",
        "Uses cards in the hand as Fusion Materials",
        "Uses cards on the player's field as Fusion Materials",
        "Uses cards in the player's Graveyard as Fusion Materials",
        "Uses cards on the opponent's field as Fusion Materials",
        "Uses cards in the player's Deck as Fusion Materials",
        "Uses cards in the player's Extra Deck as Fusion Materials",
        "Uses Spell Cards as Fusion Materials",
        "Uses Trap Cards as Fusion Materials",
        "Uses cards in the Graveyard as Fusion Materials",
        "Uses cards in the opponent's Graveyard as Fusion Materials",
        "Uses the player's banished cards as Fusion Materials",
        "Tributes Fusion Materials for Contact Fusion",
        "Banishes Fusion Materials used in a Fusion Summon",
        "Banishes Fusion Materials for Contact Fusion",
        "Sends Fusion Materials for Contact Fusion to Graveyard",
        "Returns Fusion Materials for Contact Fusion to Deck",
        "Returns Fusion Materials used in a Fusion Summon to Deck",
        "Discards Fusion Materials used in a Fusion Summon",
        "Modifies which cards can be used as Fusion Material",
        "Reduces required number of Fusion Materials",
        "Contact Fusion",
        "Contact Fusion without listed Fusion Materials",
    },
    "effect_synchro_related": {
        "Performs a Synchro Summon",
        "Uses cards in the hand as Synchro Materials",
        "Uses the opponent's monsters as Synchro Materials",
    },
    "effect_xyz_related": {
        "Performs an Xyz Summon",
        "Performs Xyz Evolution",
        "Attaches from your Graveyard as Xyz Material",
        "Attaches from your field as Xyz Material",
        "Attaches from your hand as Xyz Material",
        "Attaches from your opponent's field as Xyz Material",
        "Attaches from your opponent's Graveyard as Xyz Material",
        "Attaches from your opponent's Extra Deck as Xyz Material",
        "Attaches from your Deck as Xyz Material",
        "Attaches from your Extra Deck as Xyz Material",
        "Attaches from outside of your Deck as Xyz Material",
        "Attaches your banished cards as Xyz Material",
        "Attaches your opponent's banished cards as Xyz Material",
        "Returns Xyz Materials to the Extra Deck",
        "Adds Xyz Materials to the hand",
        "Sets Xyz Materials to your field",
        "Moves Xyz Materials",
        "Grants effect as Xyz Material",
    },
    "effect_link_related": {
        "Performs a Link Summon",
        "Uses cards in the hand as Link Materials",
        "Uses cards on the opponent's field as Link Materials",
        "Uses Spell Cards as Link Materials",
    },
    "effect_ritual_related": {
        "Performs a Ritual Summon",
        "Ritual Summons from your Graveyard",
        "Ritual Summons from your Deck",
        "Ritual Summons from your Pendulum Zone",
        "Ritual Summons from your Extra Deck",
        "Ritual Summons the player's banished monsters",
        "Can be Ritual Summoned",
    },
    "effect_pendulum_related": {
        "Performs a Pendulum Summon",
        "Goes to Pendulum Zone",
        "Places from Deck to Pendulum Zone",
        "Places from field to Pendulum Zone",
        "Places from Extra Deck to Pendulum Zone",
        "Places from Graveyard to Pendulum Zone",
        "Places from hand to Pendulum Zone",
    },
    "effect_ss_from_hand": {
        "Special Summons from your hand",
        "Special Summons itself from your hand",
        "Special Summons itself from your hand to your opponent's field",
        "Special Summons from your hand to your opponent's field",
    },
    "effect_ss_from_deck": {
        "Special Summons from your Deck",
        "Special Summons itself from your Deck",
        "Special Summons from your Deck to your opponent's field",
    },
    "effect_ss_tokens": {
        "Special Summons Tokens",
        "Special Summons Tokens to your opponent's field",
    },
    "effect_revives_from_gy_or_banished": {
        "Special Summons from your Graveyard",
        "Special Summons itself from your Graveyard",
        "Special Summons from your banishment",
        "Special Summons itself while banished",
        "Special Summons from your opponent's Graveyard to your field",
        "Special Summons from your opponent's Graveyard to your opponent's field",
        "Special Summons from your Graveyard to your opponent's field",
        "Special Summons from your banishment to the opponent's field",
        "Special Summons the opponent's banished monsters to the player's field",
        "Special Summons the opponent's banished monsters to the opponent's field",
        "Special Summons itself from your Graveyard to your opponent's field",
        "Returns banished cards to the field",
    },
    "effect_deck_manipulation": {
        "Changes the player's Deck order",
        "Places cards from the player's Deck on the top of the Deck",
        "Places cards from the player's Deck on the bottom of the Deck",
        "Places cards from the Deck on the top of the Deck",
        "Places cards from the Deck on the bottom of the Deck",
        "Places cards from the player's Graveyard on the top of the Deck",
        "Places cards from the player's Graveyard on the bottom of the Deck",
        "Places cards from the player's hand on the top of the Deck",
        "Places cards from the player's hand on the bottom of the Deck",
        "Places cards from the opponent's Graveyard on the bottom of the Deck",
        "Places cards from the opponent's Graveyard on the top of the Deck",
        "Places cards from the opponent's field on the top of the Deck",
        "Places cards from the opponent's field on the bottom of the Deck",
        "Places cards from the player's field on the top of the Deck",
        "Places cards from the player's field on the bottom of the Deck",
        "Places cards from the opponent's Deck on the top of the Deck",
        "Places cards from the opponent's Deck on the bottom of the Deck",
        "Places itself from the player's Graveyard on the top of the Deck",
        "Places itself from the player's Graveyard on the bottom of the Deck",
        "Places itself on the bottom of the Deck when it leaves the field",
        "Places itself from the player's field on the top of the Deck",
        "Places itself from the player's field on the bottom of the Deck",
        "Places itself from the player's hand on the bottom of the Deck",
        "Looks at cards from the top of the player's Deck",
        "Looks at cards from the top of the opponent's Deck",
        "Reveals cards from your Deck",
        "Reveals from the top of your opponent's Deck",
        "Reveals from the top of the player's Deck",
        "Reveals from the bottom of the player's Deck",
        "Reveals from the bottom of your opponent's Deck",
        "Changes the opponent's Deck order",
        "Reveals cards from your opponent's Deck",
        "Reveals your opponent's Deck",
        "Changes Deck order",
        "Shows the player's drawn cards",
        "Shows the opponent's drawn cards",
        "Returns to the Deck cards that would be sent to the Graveyard",
    },
    "effect_declares": {
        "Declares an Attribute",
        "Declares a Type",
        "Declares a card name",
        "Declares a card type",
        "Declares a Level",
        "Declares Pendulum Scales",
        "Declares Life Points",
        "Declares a monster card type",
    },
    "effect_return_hand_to_deck": {
        "Returns from your hand to your Deck",
        "Returns from hand to Deck",
        "Returns itself from hand to Deck",
    },
    "effect_returns_banished_to_deck_or_gy": {
        "Returns the player's banished cards to the Deck",
        "Returns the player's banished cards to the Deck by effect",
        "Returns the player's banished cards to the Graveyard",
        "Returns the opponent's banished cards to the Deck",
        "Returns the opponent's banished cards to the Graveyard",
        "Returns banished cards to the Deck",
        "Returns banished cards to the Graveyard",
        "Returns the player's banished cards to the Extra Deck",
        "Returns the opponent's banished cards to the Extra Deck",
    },
    "effect_tributes_as_effect": {
        "Tributes as an effect",
        "Tributes opponent's monsters",
        "Tributes itself as an effect",
        "Tributes from Extra Deck",
        "Tributes from Deck",
        "Makes your opponent Tribute",
    },
    "effect_banishes": {
        # All "Banishes X" variants except "for cost".
        "Banishes from your Graveyard",
        "Banishes from your opponent's field",
        "Banishes from your field",
        "Banishes from your opponent's Graveyard",
        "Banishes itself from Graveyard",
        "Banishes from field",
        "Banishes itself from field",
        "Banishes from your hand",
        "Banishes from your Deck",
        "Banishes itself when it leaves the field",
        "Banishes from your opponent's hand",
        "Banishes cards that would be sent to the Graveyard",
        "Banishes from the top of your opponent's Deck",
        "Banishes from Graveyard",
        "Banishes other cards when they leave the field",
        "Banishes monsters from Graveyard for Ritual Summon",
        "Banishes from your opponent's Extra Deck",
        "Banishes negated activations",
        "Banishes from Graveyard for Summon",
        "Banishes from field for Summon",
        "Banishes from hand for Summon",
        "Banishes from field for Summon",
    },
    "effect_banishes_facedown": {
        "Banishes face-down",
    },

    # ─────────────── 그룹 ③: 발동 시점 (Trigger) ───────────────

    "trigger_from_gy": {
        "Activates from your Graveyard",
    },
    "trigger_from_hand": {
        "Activates from your hand",
    },
    "trigger_from_banished": {
        "Activates while banished",
    },
    "trigger_upon_summon": {
        "Activates upon Special Summon",
        "Activates upon Normal Summon",
        "Activates upon Flip Summon",
        "Activates upon Synchro Summon",
        "Activates upon Xyz Summon",
        "Activates upon Tribute Summon",
        "Activates upon Fusion Summon",
        "Activates upon Ritual Summon",
        "Activates upon Pendulum Summon",
        "Activates upon Link Summon",
        "Activates upon Set",
    },
    "trigger_when_destroyed": {
        "Activates if destroyed by battle",
        "Activates if destroyed by card effect",
        "Activates if destroyed",
        "Activates if destroyed while Set",
    },
    "trigger_when_flipped_face_up": {
        "Activates upon being flipped face-up",
    },
    "trigger_sent_to_gy": {
        "Activates if sent to the Graveyard",
        "Activates if sent to the Graveyard for cost",
    },
    "trigger_when_tributed": {
        "Activates if Tributed",
    },
    "trigger_when_targeted": {
        "Activates if targeted by card effect",
        "Activates if targeted for an attack",
    },
    "trigger_during_summon_turn": {
        "Activates during the turn in which it was Normal Summoned",
        "Activates during the turn in which it was Special Summoned",
        "Activates during the turn in which it was Ritual Summoned",
        "Activates during the turn in which it was Fusion Summoned",
        "Activates during the turn in which it was Flip Summoned",
    },
    "trigger_leaves_field": {
        "Activates if it leaves the field",
        "Activates if other cards leave the field",
        "Activates if returned from the field to the hand",
        "Activates if moved to another Zone",
    },
    "trigger_used_as_material": {
        "Activates if used as Synchro Material",
        "Activates if used as Fusion Material",
        "Activates if used as Link Material",
    },
}

# Korean question labels — what the player sees in the game menu.
CLUSTER_LABELS: dict[str, str] = {

    # Cost
    "cost_tribute":              "효과 발동/소환에 릴리스(제물) 비용이 필요한 카드인가요?",
    "cost_discard":              "효과 발동에 패 버리기(디스카드) 비용이 필요한 카드인가요?",
    "cost_field_to_gy":          "필드의 카드를 묘지로 보내는 비용이 필요한 카드인가요?",
    "cost_reveal_hand":          "패 공개를 비용으로 요구하는 카드인가요?",
    "cost_send_deck_to_gy":      "덱에서 묘지로 보내는 비용이 필요한 카드인가요?",
    "cost_bounces":              "필드 카드를 패/덱으로 보내는 비용이 필요한 카드인가요?",
    "cost_return_hand_to_deck":  "패에서 덱으로 되돌리는 비용이 필요한 카드인가요?",
    "cost_banish":               "제외를 비용으로 요구하는 카드인가요?",

    # Effect
    "effect_destroys_monster":   "필드의 몬스터를 파괴하는 카드인가요?",
    "effect_destroys_st":        "필드의 마법/함정을 파괴하는 카드인가요?",
    "effect_negates_activation": "발동을 무효로 하는 카드인가요?",
    "effect_negates_effect":     "효과를 무효로 하는 카드인가요?",
    "effect_banishes":           "카드를 제외하는 효과를 가진 카드인가요?",
    "effect_banishes_facedown":  "뒷면 표시로 제외하는 카드인가요?",
    "effect_searches":           "덱에서 패로 가져오는(서치) 카드인가요?",
    "effect_salvages":           "묘지에서 패로 가져오는(샐비지) 카드인가요?",
    "effect_draws":              "드로우하는 카드인가요?",
    "effect_dumps_own_deck":     "자기 덱을 묘지로 보내는(덤핑) 카드인가요?",
    "effect_mills_opponent_deck":"상대 덱을 묘지로 보내는(상대 덱 파괴) 카드인가요?",
    "effect_dumps_own_extra":    "자기 엑스트라 덱을 묘지로 보내는 카드인가요?",
    "effect_mills_opponent_extra":"상대 엑스트라 덱을 묘지로 보내는 카드인가요?",
    "effect_bounces":            "필드 카드를 패/덱으로 되돌리는(바운스) 카드인가요?",
    "effect_sends_field_to_gy":  "필드 카드를 묘지로 보내는 효과를 가진 카드인가요?",
    "effect_changes_battle_position":"표시 형식(공격/수비)을 변경하는 카드인가요?",
    "effect_flips_face_position":"앞면/뒷면 표시를 변경하는 카드인가요?",
    "effect_discards":           "효과로 패에서 묘지로 보내는 카드인가요?",
    "effect_recycles_gy_to_deck":"묘지에서 덱으로 되돌리는 카드인가요?",
    "effect_equip_mechanic":     "원래는 장착 카드가 아닌데 장착 카드처럼 사용되거나 다른 카드에 장착되는 카드인가요?",
    "effect_sets_from_deck":     "덱에서 카드를 세트하는 카드인가요?",
    "effect_sets_from_hand":     "패에서 카드를 세트하는 카드인가요?",
    "effect_sets_from_gy_or_banished":"묘지/제외에서 카드를 세트하는 카드인가요?",
    "effect_control_change":     "몬스터의 컨트롤을 변경/조작하는 카드인가요?",
    "effect_locks":              "특정 행동을 막는(락) 카드인가요?",
    "effect_returns_banished_to_hand":"제외된 카드를 패/엑덱으로 가져오는 카드인가요?",
    "effect_forces_opponent_discard":"상대 패를 버리게 하거나 파괴하는 카드인가요?",
    "effect_forces_opponent_draw":"상대를 드로우시키는 카드인가요?",
    "effect_fusion_related":     "융합 소환 관련 효과를 가진 카드인가요?",
    "effect_synchro_related":    "싱크로 소환 관련 효과를 가진 카드인가요?",
    "effect_xyz_related":        "엑시즈 소환 관련 효과를 가진 카드인가요?",
    "effect_link_related":       "링크 소환 관련 효과를 가진 카드인가요?",
    "effect_ritual_related":     "의식 소환 관련 효과를 가진 카드인가요?",
    "effect_pendulum_related":   "펜듈럼 소환 관련 효과를 가진 카드인가요?",
    "effect_ss_from_hand":       "패에서 특수 소환하는 효과를 가진 카드인가요?",
    "effect_ss_from_deck":       "덱에서 특수 소환하는 효과를 가진 카드인가요?",
    "effect_ss_tokens":          "토큰을 특수 소환하는 효과를 가진 카드인가요?",
    "effect_revives_from_gy_or_banished":"묘지/제외에서 필드로 되돌리는(소생) 효과를 가진 카드인가요?",
    "effect_deck_manipulation":  "덱을 들여다보거나 순서를 바꾸거나 공개하는 효과를 가진 카드인가요?",
    "effect_declares":           "속성/종족/카드명 등을 선언하는 효과를 가진 카드인가요?",
    "effect_return_hand_to_deck":"패에서 덱으로 되돌리는 효과를 가진 카드인가요?",
    "effect_returns_banished_to_deck_or_gy":"제외된 카드를 덱/묘지로 되돌리는 효과를 가진 카드인가요?",
    "effect_tributes_as_effect": "효과로 릴리스시키는 카드인가요?",

    # Trigger
    "trigger_from_gy":           "묘지에서 효과를 발동하는 카드인가요?",
    "trigger_from_hand":         "패에서 효과를 발동하는 카드인가요?",
    "trigger_from_banished":     "제외 상태에서 효과를 발동하는 카드인가요?",
    "trigger_upon_summon":       "소환 시 효과를 발동하는 카드인가요?",
    "trigger_when_destroyed":    "파괴 시 효과를 발동하는 카드인가요?",
    "trigger_when_flipped_face_up":"리버스 시 효과를 발동하는 카드인가요?",
    "trigger_sent_to_gy":        "묘지로 보내졌을 때 효과를 발동하는 카드인가요?",
    "trigger_when_tributed":     "릴리스되었을 때 효과를 발동하는 카드인가요?",
    "trigger_when_targeted":     "대상이 되었을 때 효과를 발동하는 카드인가요?",
    "trigger_during_summon_turn":"소환된 턴에만 발동하는 효과를 가진 카드인가요?",
    "trigger_leaves_field":      "필드에서 벗어났을 때 발동되는 효과를 가진 카드인가요?",
    "trigger_used_as_material":  "소재로 사용되었을 때 효과를 발동하는 카드인가요?",
}

# Ordered lists per game-menu group.
COST_CLUSTERS = [
    "cost_tribute", "cost_discard", "cost_field_to_gy", "cost_send_deck_to_gy",
    "cost_banish", "cost_bounces", "cost_return_hand_to_deck", "cost_reveal_hand",
]
EFFECT_CLUSTERS = [
    "effect_destroys_monster", "effect_destroys_st",
    "effect_banishes", "effect_banishes_facedown",
    "effect_negates_activation", "effect_negates_effect",
    "effect_searches", "effect_salvages", "effect_draws",
    "effect_dumps_own_deck", "effect_mills_opponent_deck",
    "effect_dumps_own_extra", "effect_mills_opponent_extra",
    "effect_bounces", "effect_sends_field_to_gy",
    "effect_discards", "effect_recycles_gy_to_deck",
    "effect_returns_banished_to_hand", "effect_returns_banished_to_deck_or_gy",
    "effect_changes_battle_position", "effect_flips_face_position",
    "effect_equip_mechanic",
    "effect_sets_from_deck", "effect_sets_from_hand", "effect_sets_from_gy_or_banished",
    "effect_control_change", "effect_locks",
    "effect_forces_opponent_discard", "effect_forces_opponent_draw",
    "effect_fusion_related", "effect_ritual_related",
    "effect_ss_from_hand", "effect_ss_from_deck", "effect_ss_tokens",
    "effect_revives_from_gy_or_banished",
    "effect_deck_manipulation", "effect_declares",
    "effect_return_hand_to_deck", "effect_tributes_as_effect",
]
TRIGGER_CLUSTERS = [
    "trigger_from_gy", "trigger_from_hand", "trigger_from_banished",
    "trigger_upon_summon", "trigger_when_destroyed", "trigger_when_flipped_face_up",
    "trigger_sent_to_gy", "trigger_when_tributed", "trigger_when_targeted",
    "trigger_during_summon_turn", "trigger_leaves_field", "trigger_used_as_material",
]


def card_in_cluster(card, cluster_id: str) -> bool:
    """True if any of the card's Yugipedia tag values belongs to cluster."""
    needle = CLUSTERS.get(cluster_id)
    if not needle:
        return False
    for field in ("yugipedia_actions", "yugipedia_summoning", "yugipedia_misc",
                  "yugipedia_monster_spell_trap", "yugipedia_banishing"):
        for v in (getattr(card, field, None) or []):
            if v in needle:
                return True
    return False
