from django.db import models

from carddb.models import Card


class LegacyTheme(models.Model):
    card = models.OneToOneField(Card, on_delete=models.CASCADE, primary_key=True, related_name="legacy_theme")
    archetype = models.CharField(max_length=100, blank=True, help_text="YGOPRODeck 테마 이름 (영어) — 테마 작업 전까지 쓰는 임시 값")
    archetype_ko = models.CharField(max_length=100, blank=True)


class Yugipedia(models.Model):
    card = models.OneToOneField(Card, on_delete=models.CASCADE, primary_key=True, related_name="yugipedia")
    actions = models.JSONField(default=list, blank=True)
    summoning = models.JSONField(default=list, blank=True)
    misc = models.JSONField(default=list, blank=True)
    monster_spell_trap = models.JSONField(default=list, blank=True)
    banishing = models.JSONField(default=list, blank=True)
    archseries = models.JSONField(default=list, blank=True)


class EffectTag(models.Model):
    card = models.OneToOneField(Card, on_delete=models.CASCADE, primary_key=True, related_name="effect_tag")
    destroys = models.BooleanField(default=False, db_index=True)
    banishes = models.BooleanField(default=False, db_index=True)
    banishes_facedown = models.BooleanField(default=False, db_index=True)
    draws = models.BooleanField(default=False, db_index=True)
    searches = models.BooleanField(default=False, db_index=True)
    negates = models.BooleanField(default=False, db_index=True)
    bounces = models.BooleanField(default=False, db_index=True)
    special_summons = models.BooleanField(default=False, db_index=True)
    sends_to_graveyard = models.BooleanField(default=False, db_index=True)
    dumps = models.BooleanField(default=False, db_index=True)
    effect_damage = models.BooleanField(default=False, db_index=True)
    revives = models.BooleanField(default=False, db_index=True)
    salvages = models.BooleanField(default=False, db_index=True)
    locks = models.BooleanField(default=False, db_index=True)
    hand_trap = models.BooleanField(default=False, db_index=True)
    cat_destroy_monster   = models.BooleanField(default=False, db_index=True)
    cat_destroy_st        = models.BooleanField(default=False, db_index=True)
    cat_destroy_deck      = models.BooleanField(default=False, db_index=True)
    cat_destroy_hand      = models.BooleanField(default=False, db_index=True)
    cat_send_to_gy        = models.BooleanField(default=False, db_index=True)
    cat_send_to_hand      = models.BooleanField(default=False, db_index=True)
    cat_send_to_deck      = models.BooleanField(default=False, db_index=True)
    cat_banish            = models.BooleanField(default=False, db_index=True)
    cat_draw              = models.BooleanField(default=False, db_index=True)
    cat_search            = models.BooleanField(default=False, db_index=True)
    cat_change_atk_def    = models.BooleanField(default=False, db_index=True)
    cat_change_level_rank = models.BooleanField(default=False, db_index=True)
    cat_position          = models.BooleanField(default=False, db_index=True)
    cat_piercing          = models.BooleanField(default=False, db_index=True)
    cat_direct_attack     = models.BooleanField(default=False, db_index=True)
    cat_multi_attack      = models.BooleanField(default=False, db_index=True)
    cat_negate_activation = models.BooleanField(default=False, db_index=True)
    cat_negate_effect     = models.BooleanField(default=False, db_index=True)
    cat_damage_lp         = models.BooleanField(default=False, db_index=True)
    cat_recover_lp        = models.BooleanField(default=False, db_index=True)
    cat_special_summon    = models.BooleanField(default=False, db_index=True)
    cat_non_effect        = models.BooleanField(default=False, db_index=True)
    cat_token_related     = models.BooleanField(default=False, db_index=True)
    cat_fusion_related    = models.BooleanField(default=False, db_index=True)
    cat_ritual_related    = models.BooleanField(default=False, db_index=True)
    cat_synchro_related   = models.BooleanField(default=False, db_index=True)
    cat_xyz_related       = models.BooleanField(default=False, db_index=True)
    cat_link_related      = models.BooleanField(default=False, db_index=True)
    cat_counter_related   = models.BooleanField(default=False, db_index=True)
    cat_gamble            = models.BooleanField(default=False, db_index=True)
    cat_control           = models.BooleanField(default=False, db_index=True)
    cat_move_zones        = models.BooleanField(default=False, db_index=True)
    manually_reviewed = models.BooleanField(default=False, db_index=True)

    classified_at = models.DateTimeField(null=True, blank=True)
    classifier_version = models.CharField(max_length=20, default="v1")
    manually_reviewed = models.BooleanField(default=False, db_index=True)
