# Generated by Django 5.1.6 on 2025-02-21 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SummoningMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.IntegerField(choices=[(0, 'None'), (1, 'Fusion'), (2, 'Ritual'), (3, 'Synchro'), (4, 'Xyz'), (5, 'Pendulum'), (6, 'Link'), (99, 'All')], unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('category', models.CharField(choices=[('functional', 'Functional'), ('aesthetic', 'Aesthetic')], default='functional', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('strength', models.IntegerField(choices=[(0, 'Subpar'), (1, 'Non-meta'), (2, 'Near-meta'), (3, 'Meta')])),
                ('difficulty', models.IntegerField(choices=[(0, 'Easy'), (1, 'Intermediate'), (2, 'Advanced')])),
                ('deck_type', models.IntegerField(choices=[(0, 'Combo'), (1, 'Midrange'), (2, 'Control'), (3, 'Rogue')])),
                ('art_style', models.IntegerField(choices=[(0, 'Cool'), (1, 'Dark'), (2, 'Bright'), (3, 'Dreamy'), (4, 'Grand')])),
                ('summoning_methods', models.ManyToManyField(to='deck.summoningmethod')),
                ('tags', models.ManyToManyField(blank=True, to='deck.tag')),
            ],
        ),
    ]
