# Generated by Django 5.1.6 on 2025-02-21 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deck', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deck',
            name='cover_image',
            field=models.ImageField(blank=True, help_text='Upload a representative image for the deck.', null=True, upload_to='deck_covers/'),
        ),
        migrations.AddField(
            model_name='deck',
            name='description',
            field=models.TextField(blank=True, help_text="Provide details about the deck's features, usage tips, or overall concept.", null=True),
        ),
    ]
