# Generated by Django 5.1.6 on 2025-02-21 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deck', '0002_deck_cover_image_deck_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deck',
            name='art_style',
            field=models.IntegerField(choices=[(0, '멋있는'), (1, '어두운'), (2, '명랑한'), (3, '환상적'), (4, '웅장한')]),
        ),
        migrations.AlterField(
            model_name='deck',
            name='deck_type',
            field=models.IntegerField(choices=[(0, '전개'), (1, '미드레인지'), (2, '운영'), (3, '특이')]),
        ),
        migrations.AlterField(
            model_name='deck',
            name='difficulty',
            field=models.IntegerField(choices=[(0, '쉬움'), (1, '보통'), (2, '어려움')]),
        ),
        migrations.AlterField(
            model_name='deck',
            name='strength',
            field=models.IntegerField(choices=[(0, '하위권'), (1, '비티어권'), (2, '준티어권'), (3, '티어권')]),
        ),
        migrations.AlterField(
            model_name='summoningmethod',
            name='method',
            field=models.IntegerField(choices=[(0, '없음'), (1, '융합'), (2, '의식'), (3, '싱크로'), (4, '엑시즈'), (5, '펜듈럼'), (6, '링크'), (99, '다양')], unique=True),
        ),
    ]
