# Generated by Django 5.1.6 on 2025-02-21 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deck', '0004_alter_tag_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='category',
            field=models.CharField(choices=[('성능적', '성능적'), ('성능 외적', '성능 외적')], default='성능적', max_length=20),
        ),
    ]
