# Generated by Django 5.1.6 on 2025-02-21 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deck', '0005_alter_tag_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deck',
            name='strength',
            field=models.IntegerField(choices=[(0, '티어권'), (1, '준티어권'), (2, '비티어권'), (3, '하위권')]),
        ),
    ]
