# Generated by Django 5.1.6 on 2025-02-23 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deck', '0007_alter_summoningmethod_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summoningmethod',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
