# Generated by Django 5.1.6 on 2025-02-23 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deck', '0008_alter_summoningmethod_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summoningmethod',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
