# Generated by Django 5.1.6 on 2025-02-23 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deck', '0011_alter_summoningmethod_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summoningmethod',
            name='method',
            field=models.IntegerField(choices=[(1, '융합'), (2, '의식'), (3, '싱크로'), (4, '엑시즈'), (5, '펜듈럼'), (6, '링크'), (0, '소환법 없음'), (99, '다양')], unique=True),
        ),
    ]
