# Generated by Django 5.1.6 on 2025-02-27 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deck', '0015_alter_tag_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='AestheticTag',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PerformanceTag',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='deck',
            name='aesthetic_tags',
            field=models.ManyToManyField(blank=True, to='deck.aesthetictag'),
        ),
        migrations.AddField(
            model_name='deck',
            name='performance_tags',
            field=models.ManyToManyField(blank=True, to='deck.performancetag'),
        ),
    ]
