# Generated by Django 5.1.6 on 2025-02-27 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deck', '0016_aesthetictag_performancetag_deck_aesthetic_tags_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deck',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
