# Generated by Django 5.1.6 on 2025-02-27 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deck', '0017_remove_deck_tags_delete_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('category', models.CharField(choices=[('성능적', '성능적'), ('성능 외적', '성능 외적')], default='성능적', max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='deck',
            name='tags',
            field=models.ManyToManyField(blank=True, to='deck.tag'),
        ),
    ]
