# Generated by Django 5.1.6 on 2025-02-27 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deck', '0018_tag_deck_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deck',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
