# Generated by Django 5.1.6 on 2025-02-28 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deck', '0021_aesthetictag_description_performancetag_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='deck',
            name='num_views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
