# Generated by Django 5.1.6 on 2026-05-06 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0005_quizhighscore'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='archetype',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='atk',
            field=models.IntegerField(blank=True, help_text="-1 means '?'", null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='attribute',
            field=models.CharField(blank=True, db_index=True, help_text='DARK, LIGHT, WATER, FIRE, EARTH, WIND, DIVINE', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='card_type',
            field=models.CharField(blank=True, help_text='Effect Monster / Spell Card / Trap Card / ...', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='def_value',
            field=models.IntegerField(blank=True, db_column='def_value', help_text="-1 means '?'", null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='description',
            field=models.TextField(blank=True, help_text='English effect text from API', null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='frame_type',
            field=models.CharField(blank=True, help_text='effect, synchro, xyz, link, spell, trap, ...', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='korean_description',
            field=models.TextField(blank=True, help_text='Korean effect text (separate source)', null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='level',
            field=models.IntegerField(blank=True, help_text='Level for normal/effect, Rank for XYZ', null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='link_markers',
            field=models.JSONField(blank=True, help_text="['Top','Left',...]", null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='link_value',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='pendulum_scale',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='race',
            field=models.CharField(blank=True, db_index=True, help_text='Fiend, Dragon, Spellcaster, ... or Spell/Trap subcategory', max_length=50, null=True),
        ),
    ]
