# Generated by Django 5.1.6 on 2026-05-06 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0006_card_archetype_card_atk_card_attribute_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='korean_archetype',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
    ]
